-- Add more detailed specifications to vehicles table
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS drivetrain TEXT DEFAULT '4WD';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS transmission TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS fuel_tank_capacity DECIMAL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS seating_capacity INTEGER DEFAULT 5;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS cargo_capacity DECIMAL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS approach_angle_degrees INTEGER;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS departure_angle_degrees INTEGER;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS breakover_angle INTEGER;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS wading_depth DECIMAL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS horsepower INTEGER;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS torque INTEGER;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS zero_to_sixty DECIMAL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS top_speed INTEGER;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS fuel_type TEXT DEFAULT 'Gasoline';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS safety_rating DECIMAL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS warranty TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS starting_price DECIMAL;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS max_payload INTEGER;