-- Insert sample insurance providers
INSERT INTO public.insurance_providers (name, company_name, description, rating, logo_url, website_url, contact_email, contact_phone, coverage_areas, specializes_in) VALUES
('Progressive', 'Progressive Insurance Co.', 'One of the largest auto insurers in the US with competitive rates for trucks and SUVs', 4.2, 'https://www.progressive.com/content/dam/progressive-com/logos/progressive-logo.svg', 'https://www.progressive.com', 'contact@progressive.com', '1-800-776-4737', ARRAY['nationwide'], ARRAY['truck', 'SUV', 'commercial']),
('GEICO', 'Government Employees Insurance Company', 'Known for affordable rates and excellent customer service for off-road vehicles', 4.5, 'https://media.geico.com/brand/logo/primary/geico-logo-primary-reverse.svg', 'https://www.geico.com', 'info@geico.com', '1-800-861-8380', ARRAY['nationwide'], ARRAY['truck', 'SUV', 'off-road']),
('State Farm', 'State Farm Mutual Automobile Insurance Company', 'Americas largest auto insurer with specialized coverage for modified vehicles', 4.1, 'https://www.statefarm.com/content/dam/sf-www/simple-conversation-homepage/statefarm-logo.svg', 'https://www.statefarm.com', 'support@statefarm.com', '1-866-782-8332', ARRAY['nationwide'], ARRAY['truck', 'SUV', 'modified']);

-- Insert sample insurance quotes
INSERT INTO public.insurance_quotes (provider_id, vehicle_type, coverage_type, monthly_premium, annual_premium, deductible, coverage_limit, features, min_age, max_age, min_experience_years, state_code) VALUES
((SELECT id FROM insurance_providers WHERE name = 'Progressive'), 'truck', 'comprehensive', 189.99, 2279.88, 500, 100000, ARRAY['roadside_assistance', 'rental_coverage', 'gap_coverage'], 25, 65, 3, 'CA'),
((SELECT id FROM insurance_providers WHERE name = 'GEICO'), 'SUV', 'full', 156.75, 1881.00, 250, 150000, ARRAY['off_road_coverage', 'custom_parts', 'towing'], 21, 70, 2, 'TX'),
((SELECT id FROM insurance_providers WHERE name = 'State Farm'), 'pickup', 'collision', 143.50, 1722.00, 1000, 75000, ARRAY['modified_vehicle', 'performance_parts', 'track_coverage'], 23, 60, 1, 'FL');

-- Insert sample clubs
INSERT INTO public.clubs (name, description, location, country, club_type, member_count, founded_year, contact_email, website_url, image_url) VALUES
('Sierra Nevada Off-Road Club', 'Premier off-road club exploring the rugged terrain of the Sierra Nevada mountains with weekly trail runs and monthly camping events.', 'Lake Tahoe, CA', 'USA', 'off-road', 245, 1987, 'info@sierraoffroad.com', 'https://sierraoffroad.com', 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'),
('Moab Desert Runners', 'Extreme desert racing and rock crawling club based in the heart of Moab with access to world-class trails.', 'Moab, UT', 'USA', 'rock-crawling', 180, 1992, 'contact@moabrunners.org', 'https://moabrunners.org', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'),
('Pacific Northwest Trail Riders', 'Family-friendly club focusing on scenic trail rides through the beautiful forests and mountains of the Pacific Northwest.', 'Seattle, WA', 'USA', 'trail-riding', 320, 1995, 'hello@pnwtrails.net', 'https://pnwtrails.net', 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80');

-- Insert sample events
INSERT INTO public.events (title, description, location, country, start_date, end_date, event_type, difficulty_level, terrain_type, max_participants, current_participants, entry_fee, venue, club_id, image_url, external_url) VALUES
('Sierra Summit Rally 2025', 'Annual high-altitude rally through challenging mountain terrain with breathtaking views and technical rock sections.', 'Lake Tahoe, CA', 'USA', '2025-08-15 09:00:00+00', '2025-08-17 18:00:00+00', 'rally', 'expert', 'mountain', 50, 32, 450.00, 'Tahoe Rim Trail', (SELECT id FROM clubs WHERE name = 'Sierra Nevada Off-Road Club'), 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 'https://sierraoffroad.com/summit-rally'),
('Moab Rock Challenge', 'Extreme rock crawling competition featuring the most technical obstacles in Moab with prizes for multiple categories.', 'Moab, UT', 'USA', '2025-07-22 08:00:00+00', '2025-07-23 17:00:00+00', 'competition', 'expert', 'rock', 75, 68, 350.00, 'Hell''s Revenge Trail', (SELECT id FROM clubs WHERE name = 'Moab Desert Runners'), 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 'https://moabrunners.org/rock-challenge'),
('Pacific Forest Adventure', 'Family-friendly weekend camping and trail riding event through old-growth forests with guided tours and activities for all skill levels.', 'Olympic National Forest, WA', 'USA', '2025-09-05 10:00:00+00', '2025-09-07 16:00:00+00', 'camping', 'beginner', 'forest', 100, 45, 125.00, 'Hurricane Ridge', (SELECT id FROM clubs WHERE name = 'Pacific Northwest Trail Riders'), 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 'https://pnwtrails.net/forest-adventure'),
('Desert Endurance Rally', 'Multi-day endurance rally across varied desert terrain testing both driver skill and vehicle reliability.', 'Moab, UT', 'USA', '2025-10-12 07:00:00+00', '2025-10-14 19:00:00+00', 'endurance', 'intermediate', 'desert', 40, 28, 650.00, 'Canyonlands National Park', (SELECT id FROM clubs WHERE name = 'Moab Desert Runners'), 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80', 'https://moabrunners.org/endurance-rally');