// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muzlggruqnlackmbrswp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11emxnZ3J1cW5sYWNrbWJyc3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTMxNzYsImV4cCI6MjA2NzgyOTE3Nn0.xRYny_LpkUVMtoL_5Sqme5xmb-evzxLWrjpDQHGy0pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});